### ISSUE TITLE
Criar telas de login

### ISSUE THREAD

**Issue by GabrielAlbernaz-Dev** [GabrielAlbernaz-Dev/Trabalho-mobile#4]

**Comment by joaoloboalmeida** [comment]
Telas criadas: 
- Login;
-  Splash screen;
- Registro.

**Comment by GabrielAlbernaz-Dev** [comment]
Ok

**Comment by GabrielAlbernaz-Dev** [comment]
![Uploading 1649807799967-cd57d7b2-0622-4996-becf-aafaa6769e8a_.jpg…]()
![Uploading 1649807945088-19657db7-f0a0-4d09-bd7f-5fe50f13a9dd.jpg…]()

**Comment by GabrielAlbernaz-Dev** [comment]
![1649807799967-cd57d7b2-0622-4996-becf-aafaa6769e8a_](https://user-images.githubusercontent.com/40902456/163078345-513384c2-4a78-4e8b-aed9-eb207187bb70.jpg)
![1649807945088-19657db7-f0a0-4d09-bd7f-5fe50f13a9dd](https://user-images.githubusercontent.com/40902456/163078348-2240b133-945c-4740-bf8a-a3d1b7f9cdaf.jpg)
