### ISSUE TITLE
Decidir padrões de design

### ISSUE THREAD

**Issue by GabrielAlbernaz-Dev** [GabrielAlbernaz-Dev/Trabalho-mobile#5]

**Comment by Caio-Du** [comment]
Criar carrossel com filmes.

**Comment by RonaldoAzevedo** [comment]
arredondamos as bordas os botão o ícone

**Comment by Caio-Du** [comment]
Carrossel com filmes.

**Comment by RonaldoAzevedo** [comment]
Elementos arredondados, Fundo escuro, Padronização de Icones outline, Seções com labels, Diferentes padrões de Tipografia.

**Comment by GabrielAlbernaz-Dev** [comment]
Ok
