### ISSUE TITLE
Criar Telas de conteúdo

### ISSUE THREAD

**Issue by GabrielAlbernaz-Dev** [GabrielAlbernaz-Dev/Trabalho-mobile#7]

**Comment by Caio-Du** [comment]
Criando tela de contéudo, foi adicionado filmes e elenco.

**Comment by GabrielAlbernaz-Dev** [comment]
Beleza

**Comment by GabrielAlbernaz-Dev** [comment]
Foi finalizado?

**Comment by Caio-Du** [comment]
Pronto

**Comment by GabrielAlbernaz-Dev** [comment]
Okk

**Comment by GabrielAlbernaz-Dev** [comment]
![1649807945088-19657db7-f0a0-4d09-bd7f-5fe50f13a9dd](https://user-images.githubusercontent.com/40902456/163074907-6cdf744a-e4be-4192-87d6-307e44128758.jpg)

**Comment by GabrielAlbernaz-Dev** [comment]
![1649808029047-e8e6e915-4aa4-46a3-842f-7ee2cbda3448](https://user-images.githubusercontent.com/40902456/163074977-9e1ece49-960e-4c66-b59a-d3b5fd863f51.jpg)
![1649807994661-c3ed49c3-ba9a-47c8-aca1-52f4b4d642a8_](https://user-images.githubusercontent.com/40902456/163074980-03cafe9a-c2a0-48d9-8612-2ececda55b0d.jpg)
![1649807976061-527f1288-dd90-4db3-bf78-669c8148e24d_](https://user-images.githubusercontent.com/40902456/163075004-d5146777-c163-40ab-84d6-82f74d964248.jpg)
