### ISSUE TITLE
Definir nome do projeto

### ISSUE THREAD

**Issue by GabrielAlbernaz-Dev** [GabrielAlbernaz-Dev/Trabalho-mobile#8]

**Comment by italoyan** [comment]
P.I.D.B

**Comment by GabrielAlbernaz-Dev** [comment]
Votação para nome do projeto:
- VFlix
- Ozama
- EasyFilms
- PIDB

**Comment by italoyan** [comment]
VFlix

**Comment by GabrielAlbernaz-Dev** [comment]
Beleza

**Comment by pvinicius1337** [comment]
IziMovie

**Comment by GabrielAlbernaz-Dev** [comment]
![1649807945088-19657db7-f0a0-4d09-bd7f-5fe50f13a9dd](https://user-images.githubusercontent.com/40902456/163075186-942cda47-d394-40f8-9ede-096114a83682.jpg)
